---
title: "Untitled"
output: html_document
---


this is a copy of all code neccessary to produce the 4-panel figure for the publication (copied from analysis_new.rmd) 

```{r setup, include=FALSE}
library(tidyverse)
library(maps)
library(geosphere)
library(fcuk)
library(metafor)
library(viridis)
```

```{r load}
studies <- read.table("lit_extract/mcmcresults.txt")
studies<-studies[order(studies$order),]
studies$col<-as.numeric(studies$order) #numbers from 1:8
studies$col<-viridis(8)[studies$col]
names(studies)[5]<-"order"

url<-"ghcnd-stations.txt"
locations<-read.fwf(
  file=url
  ,sep="!",na.strings=c("NA","-999.9"),
  widths=c(11, 9, 10, 7,2,35)
)

reslist<-read.table("clim_calc/output/results_100-5.txt",na.string = c("NA","-9999","-999.9"))
names(reslist)<-c("ID","meanwinter","sd_winter","p","nyears","ndays_300","ndays_350","ndays_365")
reslist<-reslist[1:26804,]
climate<-merge(locations,reslist,by=1)
rm(reslist)
names(climate)<-c("ID","lat","lon","alt","name","no_idea","meanwinter","sd_winter", "p",  "nyears" ,  "ndays_300"  ,"ndays_350",  "ndays_365" )
climate<-climate[!is.na(climate$meanwinter),] 
beta<-read.table("clim_calc/output/beta.txt",header=T)
climate<-merge(climate,beta,by=1)
climate<-climate[climate$lat<70,] #at higher latitudes winter onset is at midsummer
climate$dl <- daylength(climate$lat,climate$meanwinter+182)
climate <- climate[climate$sd_winter < 30,] #removes 4.2% of the stations, but these are mostly those with very bad data coverage
```

```{r plot}
svg("fig3.svg",width=7*4*1.618, height = 7*4,pointsize=48)
par(mfrow = c(2,2),mar = c(5,5,1,1)+0.1)

#####PANEL A#####
r<-studies$upper_cdl-studies$lower_cdl
r[r<(1/6)]<-1/6  #all reaction norms with credible interval of 10 min or less have same weight
vi <- (r / (2*1.96))^2 #calculation of variance from CI

metaf<-rma.mv(yi = med_cdl ~ degN, V=vi, random = ~(1|order/spec/popid), data = studies)
n<-table(studies$order)
names(n)<- paste(names(n)," (", n, ")", sep = "") #will be used for plotting later, better laod it together with the model so it wont get lost

studies$r<-r
max.size<-((1/6)/(2*1.96))^2; max.size <- 1/max.size 
plot(x=studies$degN, y=studies$med_cdl, pch=21, cex=0.3+1.5*(1/vi)/max.size, col=1, bg=studies$col, main = "", xlab = "Latitude (°N)", ylab = "Critical photoperiod (h)",bty="n", xaxt="n", cex.axis = 1.1, cex.lab=1.3) #cex ranges from 0.3 to 1.5, with 1.5 for those with heighest weight (ci = 10 min)
legend("topleft",legend=names(n), col=rep(1,8), pt.bg=unique(studies$col), pch=21, bty="n", ncol=1,cex=0.9)
coffs <-  coef(metaf)
lines(x= range(studies$degN),y = coffs[1]+coffs[2]*range(studies$degN),lwd=4,lty=1)
axis(1,at=c(0,20,30,40,50,60,70,80),cex.axis=1.1, cex.lab = 1.3)

segments(x0=studies$degN[studies$r<2], y0 = studies$upper_cdl[studies$r<2], y1=studies$lower_cdl[studies$r<2] ,col="darkgrey") 
ord<-studies[order(studies$r,as.numeric(studies$order),decreasing = c(T,F), method = "radix"),] 
vi.new <- (ord$r / (2*1.96))^2
for (i in 1:nrow(ord)){
  points(x=ord$degN[i] ,y=ord$med_cdl[i], pch=21, col=1, bg=ord$col[i], cex=(0.3+1.5*(1/vi.new)/max.size)[i])
}
 text(68,10,"A",cex=2)
 
##### combine climate and studies
studies$meanwinter<-NA
studies$sd_winter<-NA
studies$p<-NA
studies$nyears<-NA
studies$beta<-NA 
studies$sd_sd<-NA 
studies$n_s<-NA

for ( i in 1:nrow(studies)){
  #reduce to +-5 °
  sub<-climate[between(climate$lat,studies[i,"degN"]-5,studies[i,"degN"]+5)& between(climate$lon,studies[i,"degE"]-5,studies[i,"degE"]+5),]
    sub$diffN<-sub$lat-studies[i,"degN"] #calculate distance in latitude
    sub$diffE<-sub$lon-studies[i,"degE"] #same for longitude
    sub$diff<-sqrt(sub$diffN^2+sub$diffE^2) #euclidian distance
    sub<-arrange(sub,diff)[1:5,] #sort and take 5 lowest values = 5 closest stations
  studies$meanwinter[i]<-weighted.mean(sub$meanwinter,1/sub$diff)
  studies$sd_winter[i]<-weighted.mean(sub$sd_winter,1/sub$diff)
  studies$p[i]<-weighted.mean(sub$p,1/sub$diff)
  studies$nyears[i]<-weighted.mean(sub$nyears,1/sub$diff)
  studies$beta[i]<-weighted.mean(sub$beta,1/sub$diff)
  studies$sd_sd[i]<-sd(sub$sd_winter) #quality control. the predictability of nearby stations should be similar to each other
  studies$n_s <- nrow(sub) #a location may not have 5 stations around
}
studies<-studies[!(is.na(studies$meanwinter)|is.na(studies$med_e)),]#425 left
studies$meanwinter<-studies$meanwinter + 180

#####PANEL B#####
r<-studies$upper_e-studies$lower_e
r[r<7]<-7 #changes < 1 wk are irrelevant  
vi <- (r / (2*1.96))^2
mw<-rma.mv(yi = med_e ~ meanwinter, V=vi, random = ~(1|order/spec/popid), data = studies)

n<-table(studies$order) #numbers differ!
names(n)<- paste(" (", n, ")", sep = "")
par(mar=c(5,4,1,2)+0.1)

studies$r<-r
max.size<-(7/(2*1.96))^2; max.size <- 1/max.size 
plot(x=studies$meanwinter, y=studies$med_e, pch=21, cex= 0.3+1.5*(1/vi)/max.size , col=1, bg=studies$col, main = "", xlab = "Mean winter onset (ordinal day)", ylab = "Mean diapause timing (ordinal day)",bty="n", cex.axis = 1.1, cex.lab=1.3, xlim=c(170,400),ylim = c(170,400)) #cex again set so that max ptsize = 2

legend("topleft",legend=names(n), col=rep(1,8), pt.bg=unique(studies$col), pch=21, bty="n", ncol=1,cex=0.9)
coffs <-  coef(mw)

lines(x= range(studies$meanwinter),y = coffs[1]+coffs[2]*range(studies$med_e),lwd=4,lty=1)

segments(x0=studies$meanwinter[r<30],y0 = studies$lower_e[r<30],y1=studies$upper_e[r<30],col="darkgrey") #credible intervals > 1 month are not shown
ord<-studies[order(studies$r,as.numeric(studies$order),decreasing = c(T,F), method = "radix"),] 
vi.new <- (ord$r / (2*1.96))^2

for (i in 1:nrow(ord)){
  points(x=ord$meanwinter[i] ,y=ord$med_e[i], pch=21, col=1, bg=ord$col[i],cex=(0.3+1.5*(1/vi.new)/max.size)[i])
}
text(380,390, "B", cex =2)
#####

#####PANEL C#####
r <- studies$upper_r-studies$lower_r
r[r<0.05]<-0.05 #changes < 0.05 are irrelevant
vi<- (r / (2*1.96))^2 

studies$yti <- transf.logit(studies$med_r)
studies$vti <- vi / (studies$med_r * (1 - studies$med_r))^2
mod <- rma.mv(yti ~ sd_winter, vti, random = ~ 1 | order/spec/popid, data=studies)

x<-seq(5,25,length.out=1000) #will be used to plot prediction line
y=coef(mod)[1]+x*coef(mod)[2] #inverse logit transform this to get prediction

max.size<-(0.05/(2*1.96))^2; max.size <- 1/max.size 
studies$r <- r
par(mar= c(5,5,1,1)+0.1)

plot(x=studies$sd_winter, y=studies$med_r, pch=21, cex= 0.3+1.5*(1/vi)/max.size , col=1, bg=studies$col, main = "", xlab = "Standard deviation in winter onset (days)", ylab = "Ratio of variance components",bty="n", cex.axis = 1.1, cex.lab=1.3,xlim=c(0,25), ylim=c(0,1)) #cex again set so that max ptsize = 2
legend("topleft",legend=names(n), col=rep(1,8), pt.bg=unique(studies$col), pch=21, bty="n", ncol=1,cex=0.9)
coffs <-  coef(mod)
lines(x= x,y=transf.ilogit(y),lwd=2)

segments(x0=studies$sd_winter[studies$r< 0.1],y0 = studies$lower_r[studies$r<.1],y1=studies$upper_r[studies$r<0.1],col="darkgrey") 
studies$cex <- 0.3+1.5*(1/vi)/max.size
ord<-studies[order(studies$r,as.numeric(studies$order),decreasing = c(T,F), method = "radix"),]
for (i in 1:nrow(ord)){
  points(x=ord$sd_winter[i] ,y=ord$med_r[i], pch=21, col=1, bg=ord$col[i], cex=ord$cex[i])
}
 text(24,0.95, "C", cex= 2)
#####

#####PANEL D#####
r<-studies$upper_e-studies$lower_e
r[r<7]<-7 #changes < 1 wk are irrelevant  
vi <- (r / (2*1.96))^2
studies$res_mw<-rstandard(mw)$z
cbh_dl <- rma.uni(res_mw~sd_winter, vi = vi, data= studies)

par(mar=c(5,4,1,2)+0.1)
plot(studies$res_mw ~ studies$sd_winter, pch=21, cex= 0.3+1.5*(1/vi)/(max(1/vi)) , col=1, bg=studies$col, main = "", ylab = "Residuals diapause timing", xlab = "Standard deviation in winter onset (days)",bty="n", cex.axis = 1.1, cex.lab=1.3,xlim=c(0,26), ylim=c(-3,4)) 
legend("topleft",legend=names(n), col=rep(1,8), pt.bg=unique(studies$col), pch=21, bty="n", ncol=1,cex=0.9)
abline(coef(cbh_dl),lwd=2)
text(24, 3.5, "D", cex = 2)
#####


dev.off()
```


